#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Project Baru             #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & 10 Buster 64 bit               #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Modified by Rizky Vib                      #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# Rizky Vib                                   #"
echo -e "# Allah                                         #"
echo -e "# My Family                                     #"
echo -e "# Google                                        #"
echo -e "# Owner VPS                                     #"
echo -e "#                                               #"
echo -e "#                                               #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="